### ISSUE TITLE
Are there any references for the dynamics used in the SimulationModel?

### ISSUE THREAD

**Issue by m6c7l** [bridgecommand/bc#21]
Could you provide references which you have used and which
1)  describe or derive the dynamics (motion of the ships, i.e. translation and rotation) used in the simulation model and
2)  explain the model parameters for particular ships used in BC (at least how you estimated them)?

**Comment by bridgecommand** [comment]
The model parameters are described in https://www.bridgecommand.co.uk/Doc/newmodels.php
The linear parameters (like DynamicsSpeedA, DynamicsSpeedB) were estimated using a simple calculation sheet, like at https://www.bridgecommand.co.uk/data/_uploaded/file/dynamics_calculator.xls
The rotation parameters were generally tuned by trial and error, but an equivalent process could be applied.

In principle, it would be nice to define the dynamics in terms of the ship's known response, and calculate the physical parameters to match this automatically within Bridge Command. I suspect that this wouldn't be too hard, but I haven't had a proper look at this.

Additionally, it would be nice to look more physically at the wave making drag effects, rather than the simple speed^1 and speed^2 coefficients used currently.
